# Generated by Django 6.0.5 on 2026-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefonnummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
