# Generated by Django 6.0.5 on 2026-05-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_bio_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telefonnummer',
        ),
    ]
