# Generated by Django 6.0.5 on 2026-05-19 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_remove_ticket_boards_ticket_board_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boards',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Task',
        ),
    ]
